# Шаблон Docker-Compose для запуска на сервере

# Команды для полного перезапуска на сервере
# docker-compose stop && \
# docker-compose rm -f && \
# docker-compose pull && \
# docker-compose up -d

# Команда для вывода всех логов контейнера
# https://docs.docker.com/compose/reference/logs/
# docker-compose logs -f -t --tail="all"
# docker-compose logs --tail="all" > logs_$(date +%Y-%m-%d_%H-%M-%S).log

version: "3.3"
services:
    file_upload_proxy:
        image: devnul/file_upload_proxy
        container_name: file_upload_proxy
        restart: unless-stopped
        # env_file:
        #     - env/test_environment_docker.env
        volumes:
            - ${PWD}/google_service_account.json:/var/google_service_account.json
        environment:
            - RUST_BACKTRACE=full
            - RUST_LOG=debug
            - UPLOADER_API_TOKEN=
            - UPLOADER_GOOGLE_BUCKET_NAME=
            - UPLOADER_GOOGLE_CREDENTIALS_FILE=/var/google_service_account.json
            - UPLOADER_PORT=8888
        ports:
            - 8888:8888
    # network_mode: host