# Шаблон Docker-Compose для запуска на сервере

version: "3.3"
services:
    app:
        image: devnul/file_upload_proxy
        container_name: file_upload_proxy
        restart: unless-stopped
        # env_file:
        #     - env/test_environment_docker.env
        volumes:
            - ${PWD}/google_service_account.json:/var/google_service_account.json
        environment:
            - RUST_BACKTRACE=full
            - UPLOADER_API_TOKEN=
            - UPLOADER_GOOGLE_BUCKET_NAME=
            - UPLOADER_GOOGLE_CREDENTIALS_FILE=/var/google_service_account.json
            - UPLOADER_PORT=8888
        ports:
            - 8888:8888
    # network_mode: host