settings:
  port: 8080
projects:
  pi2:
    api_token: "test_api_token_value_pi2"
    google_storage_target:
      credentials_file: "env/test_google_service_account.json"
      bucket_name: "pi2-prod"
    slack_link_dub:
      token: "xoxb-3152873974-1566924779632-t1fvjXIUm5qZwQ7OpYoPcd07"
      targets: ["@U0JU3ACSJ", "#CQL2AKQ80"]
      qr_code: true
      text_before: "TEST_PREFIX"
  mm:
    api_token: "test_api_token_value_mm"
    google_storage_target:
        credentials_file: "env/test_google_service_account.json"
        bucket_name: "pi2-prod"
    slack_link_dub:
        token: "xoxb-3152873974-1566924779632-t1fvjXIUm5qZwQ7OpYoPcd07"
        targets: ["@U0JU3ACSJ", "#CQL2AKQ80"]
        qr_code: true
        text_before: "TEST_PREFIX"