version: "3.3"
services:
    file_upload_proxy:
        image: devnul/file_upload_proxy
        container_name: file_upload_proxy
        restart: unless-stopped
        volumes:
            - ${PWD}/google_service_account.json:/var/google_service_account.json
        environment:
            - RUST_BACKTRACE=full
            - RUST_LOG=file_upload_proxy=trace,warn
            - UPLOADER_API_TOKEN=
            - UPLOADER_GOOGLE_BUCKET_NAME=
            - UPLOADER_GOOGLE_CREDENTIALS_FILE=/var/google_service_account.json
            - UPLOADER_PORT=8090
        ports:
            - 8090:8090
